**Basic operations using Pytorch**

In [1]:
import torch as t
import numpy as np

In [2]:
data=[[1,2],[3,4]]
x_data=t.tensor(data)

**From NumPy array**

In [3]:
np_array=np.array(data)
x_np=t.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**Ones Tensor**

In [4]:
type(x_np)

torch.Tensor

In [5]:
x_ones=t.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

**Random Tensor**

In [6]:
x_rand=t.rand_like(x_data,dtype=t.float)
x_rand

tensor([[0.6949, 0.0077],
        [0.4198, 0.2433]])

**Attributes of a tensor-shape,data type and the device on which they are stored**

In [8]:
tensor=t.rand(3,4)
print("Shape of tensor",tensor.shape)
print("Datatype of the tensor ",tensor.dtype)
print("Device tensor is stored on",tensor.device)

Shape of tensor torch.Size([3, 4])
Datatype of the tensor  torch.float32
Device tensor is stored on cpu


**From CPU to GPU**

In [9]:
if t.cuda.is_available():
  tensor=tensor.to("cuda")
print("Now tensor is stored on:",t.device)

Now tensor is stored on: <class 'torch.device'>


**Indexing and slici**ng